
midterm: midterm.tex reference.bib	
	latex midterm.tex
	bibtex midterm
	latex midterm.tex
	pdflatex midterm.tex
	rm *.log *.aux *.bbl *.blg *.dvi *.out

proposal: proposal.tex reference.bib	
	latex proposal.tex
	bibtex proposal
	latex proposal.tex
	pdflatex proposal.tex
	rm *.log *.aux *.bbl *.blg *.dvi *.out

clean:
	rm *.pdf
